### ISSUE TITLE
User WeekStartDay preference determines the order of the data

### ISSUE THREAD

**Issue by khalwat** [craftcms/store-hours#19]
Craft lets you change what your starting day of the week is (either Sunday or Monday) as a per-user preference.

Store Hours nicely takes this into account by presenting the Store Hours entry data in the field type based on this preference.

The problem is that this data is serialized in a zero-based array of DateTime objects, with no indication of what _day_ is associated with what hours.

So if a Monday-first user preference is set, the first item in the array will be the hours for Monday. If a Sunday-first user preference is set, the first item in the array will be the hours for Sunday.

In the stored data, there's no indication of what the first day is, it varies depending on who edited the entry last.

I'd suggest normalizing the stored data so that it's always Sunday-first (and thus the example code in the README.md will work). That, or store with the hours data what day of the week is first.

**Comment by DiederikVanHoorebeke** [comment]
The fix did not help, unfortunately.

In the config `'defaultWeekStartDay' => 1`. In the backend I had to change my personal settings in order to view the changes in the fieldtype, as expected.

But when looping through the days in twig, it starts with Sunday.

![image](https://user-images.githubusercontent.com/3625639/32561015-6d6319a8-c4ab-11e7-84d9-d129fc70bb6d.png)
![image](https://user-images.githubusercontent.com/3625639/32561034-798be250-c4ab-11e7-9f9c-e41b08f1e3ac.png)

**Comment by brandonkelly** [comment]
It is expected that the front-end would always start with Sunday.

**Comment by DiederikVanHoorebeke** [comment]
That worked perfectly. Thanks!

**Comment by brandonkelly** [comment]
Just released Store Hours 1.2.2 for Craft 2 and 2.0.5 for Craft 3, with this fix.
